# Main Menu Starts Here...

  [[main]]
    name = "Home"
    url = "/"
    weight = "1"

  [[main]]
    name = "Buyers Guide"
    url = "/buying-guide/"
    weight = "2"
    
  [[main]]
    name = "Knowledge Base"
    url = "/knowledge-base/"
    weight = "3"

# Footer Menu Starts Here...

  [[footer]]
    name = "Terms and Conditions"
    url = "/terms-of-service/"
    weight = "1"

  [[footer]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = "2"

  [[footer]]
    name = "Affiliate Disclosure"
    url = "/affiliate-disclosure/"
    weight = "3"

  [[footer]]
    name = "About US"
    url = "/about-us/"
    weight = "4"

  [[footer]]
    name = "Contact US"
    url = "/contact-us/"
    weight = "5"
    
  [[footer]]
    name = "Sitemap"
    url = "/sitemap.xml/"
    weight = "5"
