logo = "/uploads/logo.png"
icon = "/uploads/favicon-32x32.png"
tagline = "Best Techs Reviewed"
contacteMail = "gamingtechies76@gmail.com"
headerText = ""
footerText = "Gaming Techies © 2021. All rights reserved."

[colors]
mainColor = "#040404"
textColor = "#ffffff"
linkColor = "#03a0ff"

[open_graph]
meta_Description = "Gaming Techies is a professional online website that keeps you updated with all the gaming techs reviews, news and latest information."
image = "https://finaldesktop.com/img/final-desktop-img.jpg"
FacebookPublisher = ""

[verifications]
googleSiteVerify = "<meta name=\"google-site-verification\" content=\"QMntww82yYU7R6IF2gp8eVcT1m3uy788E5ZfFTnfF2I\" />"
BingWebmaster = "<meta name=\"msvalidate.01\" content=\"6D95BEBC76C7BC692B270BC832560CB0\" />"
PinterestVerify = ""

[social_accounts]
sitefbAccount = "https://www.facebook.com/gamingtechiesofficial"
sitetwitterAccount = "https://www.twitter.com/gamingtechies76"
siteinstagramAccount = "https://www.instagram.com/gamingtechies76/"
sitepinterestAccount = "https://www.pinterest.com/gamingtechies76/"
siteYouTubeAccount = "https://www.youtube.com/channel/UCV1YUero4LNDkktpq6ScEjw"

[home_section]
section1 = "Style 2"
section1Cat = "Buying Guides"
section2 = "Style 2"
section2Cat = "Buying Guides"
section3 = "Style 2"
section3Cat = "Learning Guides"
section4 = "Style 2"
section4Cat = "Learning Guides"

[post_setting]
featured_img = false