logo = ""
icon = ""
tagline = "Best Techs Reviewed"
contacteMail = "gamingtechies76@gmail.com"
headerText = ""
footerText = "Gaming Techies © 2021. All rights reserved."

[colors]
mainColor = "#040404"
textColor = "#ffffff"
linkColor = "#03a0ff"

[open_graph]
meta_Description = "Gaming Techies is a professional online website that keeps you updated with all the gaming techs reviews, news and latest information."
image = "https://finaldesktop.com/img/final-desktop-img.jpg"
FacebookPublisher = ""

[verifications]
googleSiteVerify = "<meta name=\"google-site-verification\" content=\"QMntww82yYU7R6IF2gp8eVcT1m3uy788E5ZfFTnfF2I\" />"
BingWebmaster = "<meta name=\"msvalidate.01\" content=\"6D95BEBC76C7BC692B270BC832560CB0\" />"

[social_accounts]
sitefbAccount = "https://www.facebook.com/gamingtechiesofficial"
sitetwitterAccount = "https://www.twitter.com/gamingtechies76"
siteinstagramAccount = "finaldesktop"
sitepinterestAccount = "finaldesktop"
siteYouTubeAccount = "https://www.youtube.com/channel/UCV1YUero4LNDkktpq6ScEjw"

[home_section]
section1 = "Off"
section1Cat = "Category 2"
section2 = "Off"
section2Cat = "Category 1"
section3 = "Off"
section3Cat = "Category 1"
section4 = "Off"
section4Cat = "Category 1"

[post_setting]
featured_img = false