logo = "/uploads/logo.png"
icon = "/uploads/fav_icon.png"
tagline = "Computers & Gaming Made Easy"
contacteMail = ""
headerText = "**Techno Clutch is supported by its audience. When you purchase through our links, we may earn an affiliate commission at no additional cost to you.**"
footerText = "Techno Clutch © 2021. All Rights Reserved."

[colors]
mainColor = "#040404"
textColor = "#ffffff"
linkColor = "#2871de"
ctaColor = "#2871de"

[fonts]
bodyFont = "Poppins"
heading = "Poppins"

[open_graph]
meta_Description = "Techno Clutch is a Brand where we review hundreds of computer gadgets weekly and publish only the worthy products. We post unbiased reviews only."
image = ""
FacebookPublisher = ""

[verifications]
googleSiteVerify = ""
BingWebmaster = ""
PinterestVerify = ""

[social_accounts]
sitefbAccount = ""
sitetwitterAccount = ""
siteinstagramAccount = ""
sitepinterestAccount = ""
siteYouTubeAccount = ""

[home_section]
section1 = "Style 2"
section1Cat = "Buying Guides"
section2Cat = "Monitors"
section3Cat = "Motherboards"
section4Cat = "Learning Guides"

[post_setting]
featured_img = false