languageCode = "en-us"
DisqusShortname = ""
baseURL = "https://technoclutch.com"
googleAnalytics = "<!-- Global site tag (gtag.js) - Google Analytics --> <script async src=\"https://www.googletagmanager.com/gtag/js?id=G-L6ZB39BLEG\"></script> <script>   window.dataLayer = window.dataLayer || [];   function gtag(){dataLayer.push(arguments);}   gtag('js', new Date());    gtag('config', 'G-L6ZB39BLEG'); </script>"
title = "Techno Clutch"
paginate = "14"
assetDir = "static"

[permalinks]
posts = "/:title/"
pages = "/page/:title/"
categories = "/:title/"
tags = "/:title/"

[related]
includeNewer = true
threshold = 80
toLower = false

[[related.indices]]
name = "categories"
weight = 100

[[related.indices]]
name = "tags"
weight = 100

[taxonomies]
category = "categories"
tag = "tags"
author = "author"